api:
  port: 4001

redis:
  #url: redis://h:pd84c59ffd70de057d03f71c553bf6e1a6a1ad076ee9b3ff89bc2e6115be72fde@ec2-52-202-26-118.compute-1.amazonaws.com:14009
  url: redis://localhost:6379
  ttl:
    challongeTournaments: 600
  flushAll: false

database:
  mongodb:
    #url: mongodb://mth40k_usr:nueva123@ds263248.mlab.com:63248/heroku_kzt720hp
    url: mongodb://localhost/mth40?retryWrites=true&w=majority
    debug: false
  mysql:
    #host: relatosdelaherejia.cl
    #user: relatosd_wh40k
    #password: Nueva123.
    #db_instance: relatosd_wh40k
    host: u0zbt18wwjva9e0v.cbetxkdyhwsb.us-east-1.rds.amazonaws.com	
    user: fgwr0eqvwtaijamb
    password: tsp0gaybdzyuaeuv
    db_instance: m7vety412v628e4l

challonge:
  api_key: blFKNnvFaySPiWbTKkCUSdoxvf0WieaMrcWsMztX
  base_url: https://api.challonge.com/v1

wahapedia:
  armies_url: /wh40k8ed/the-rules/playing-this-game/
  base_url: http://wahapedia.ru