openapi: 3.0.0
info:
  $ref: ./info.yaml
tags:
  - name: roster-api
    description: All Roster Battlescribe Services
  - name: challonge-api
    description: Servicios de challonge API para torneos
  - name: army-api
    description: 'Army, Factions, SubFactions API'
  - name: wahapedia-api
    description: 'Warhammer 40K Information, Factions, Rules, Stratagems'
  - name: config-api
    description: 'Config wh40 api, like Redis and others'
paths:
  /roster/save:
    post:
      tags:
        - roster-api
      summary: Save Roster
      description: Guarda el Roster de Battlescribe en Mongodb
      operationId: saveRoster
      responses:
        '200':
          description: 'Resultado de la lista de tournaments[]'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Roster'
        '400':
          description: Mala petición
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                roster_json:
                  description: Json Roster here.
                  type: string
                  default: >-
                    {status:'VALIDATE', name:'Astra Millitarum-OT500-Primaris
                    Psyker'}
                roster_file:
                  description: File Roster here. (ros extension)
                  type: string
                  format: binary
              required:
                - roster_json
                - roster_file
  /roster/rtournament:
    get:
      tags:
        - roster-api
      summary: Obtiene un roster Tournament Obj
      operationId: getRosterTournament
      description: |
        Obtiene el rouster tournament por tournamentId y participantId.
      parameters:
        - name: tournamentId
          in: query
          description: Challonge Tournament Id
          required: true
          schema:
            type: integer
            default: 7968393
        - name: participantId
          in: query
          description: Challonge Participant Id
          required: true
          schema:
            type: integer
            default: 112433886
      responses:
        '200':
          description: Resultado Tournament
          content:
            application/json:
              schema:
                type: array
                items: {}
        '400':
          description: Mala petición
  /roster/list:
    get:
      tags:
        - roster-api
      summary: List Rosters
      description: Entrega la lista de rosters que hay en la base de datos
      operationId: listRosters
      parameters:
        - name: projections
          in: query
          description: Projections fields separate by space
          required: false
          schema:
            type: string
            default: name teamOwner status
      responses:
        '200':
          description: 'Resultado de la lista de rosters[]'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Roster'
        '400':
          description: Mala petición
  /roster/validate:
    post:
      tags:
        - roster-api
      summary: Validate Roster
      description: 'Valida el Roster de Battlescribe contra Challonge, wahapedia.ru'
      operationId: validateRoster
      responses:
        '200':
          description: 'Resultado de la lista de tournaments[]'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Roster'
        '400':
          description: Mala petición
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                roster_json:
                  description: Json Roster here.
                  type: string
                  default: >-
                    {status:'VALIDATE', name:'Astra Millitarum-OT500-Primaris
                    Psyker'}
              required:
                - roster_json
  /wahapedia/factions:
    get:
      tags:
        - wahapedia-api
      summary: Lista de Facciones y SubFacciones
      operationId: getFactions
      description: |
        Obtiene la lista de Facciones y SubFacciones en Wahapedia.
      responses:
        '200':
          description: Resultado de exec del servicio
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Mala petición
  /config/redis/clear:
    get:
      tags:
        - config-api
      summary: Borra la cache de redis completa
      operationId: flushall
      description: Elimina todas las keys de Redis
      responses:
        '200':
          description: Resultado operación Redis Flushall
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Mala petición
  /challonge/tournaments:
    get:
      tags:
        - challonge-api
      summary: Lista de Torneos
      operationId: listTournaments
      description: |
        Obtiene la lista de Torneos en Challonge.
      responses:
        '200':
          description: 'Resultado de la lista de tournaments[]'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tournament'
        '400':
          description: Mala petición
  /challonge/matches:
    get:
      tags:
        - challonge-api
      summary: Lista de Partidas
      operationId: listMatches
      description: |
        Obtiene la lista de Juegos por TournamentId en Challonge.
      parameters:
        - name: tournamentId
          in: query
          description: Challonge Tournament Id
          required: true
          schema:
            type: integer
            default: 7968317
      responses:
        '200':
          description: 'Resultado de la lista de matches[]'
          content:
            application/json:
              schema:
                type: array
                items: {}
        '400':
          description: Mala petición
  /challonge/tournament:
    get:
      tags:
        - challonge-api
      summary: Obtiene un torneo de Challonge
      operationId: getTournament
      description: |
        Obtiene el Torneo de Challonge, opcionales los participantes y partidas.
      parameters:
        - name: tournamentId
          in: query
          description: Challonge Tournament Id
          required: true
          schema:
            type: integer
            default: 7968317
        - name: include_participants
          in: query
          description: Include Participants Flag
          required: false
          schema:
            type: integer
            default: 1
        - name: include_matches
          in: query
          description: Include Matches Flag
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Resultado Tournament
          content:
            application/json:
              schema:
                type: array
                items: {}
        '400':
          description: Mala petición
  /army/list:
    get:
      tags:
        - army-api
      summary: Lista de Armadas
      operationId: listArmy
      description: |
        Obtiene la lista de Armadas en MTH40k DB.
      responses:
        '200':
          description: 'Resultado de la lista de Army[]'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Army'
        '400':
          description: Mala petición
servers:
  - url: /
components:
  schemas:
    Faction:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
    Roster:
      type: object
      properties:
        name:
          type: string
    Army:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Xenos
        code:
          type: string
          example: XEN
        factions:
          type: array
          items:
            $ref: '#/components/schemas/Faction'
    tournament:
      type: object
      properties:
        id:
          type: integer
          example: 7968393
        name:
          type: string
          example: '[ELI] Adeptus Astartes {OT500-V01}'
        url:
          type: string
        tournament_type:
          type: string
        game_name:
          type: string
        state:
          type: string
        event_id:
          type: integer
          example: 27010
        started_at:
          type: string
        completed_at:
          type: string